### ISSUE TITLE
문제점 : 네이버로 회원 가입 시 여행 스타일을 설정하지 못하는 문제 발생

### ISSUE THREAD

**Issue by Nail0606** [Trip-Record/Web#19]
원인 : 여행 스타일 설정이 회원 가입의 절차 중 하나이기 때문에 네이버로 회원가입하려는 사람들에게 해당 절차를 밟게 할 수 없음.

해결법 : 여행 스타일 페이지를 분리, 기본 여행 스타일(ex) 미정 등... ) 기본 설정 후 마이페이지에서 수정할 수 있게 함.

해결법 2 : 회원가입 자체에는 여행 스타일 입력하지 않게 함 -> 글쓰기 등 기능을 수행할 때 확인 절차를 거치게 함.

**Comment by Goongam** [comment]
해결방법 - 회원가입 끝나면 주는 알림에 마이페이지에서 스타일 수정 가능하다고 알려줌 + 회원가입 완료 알림
기본적으로 미정
